name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all tags + history
      - name: Get previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo "${{ steps.previous_tag.outputs.tag }}"
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.previous_tag.outputs.tag }}
      - id: next_version
        uses: zwaldowski/semver-release-action@v1
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release dir
        run: |
          # TODO <-= this should be the _current_ major version
          cp -R src/imports/ releases/v${{ steps.semver_parser.outputs.major }}.0
          cp -R src/terra-core/ releases/v${{ steps.semver_parser.outputs.major }}.0
          git config user.name "TIM Release Bot"
          git config user.email "<>"
          git add .
          git commit -m 'Releasing version ${{ steps.next_version.outputs.tag }}'
          git tag ${{ steps.next_version.outputs.next_version }}
          git push ${{ steps.next_version.outputs.next_version }}

#      - uses: zwaldowski/semver-release-action@v1
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#        with:
#          bump: minor
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          sha: ${{ steps.git_commit.outputs.sha }}
#          prefix: v
#


