name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Previous tag
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Echo Next Tag
        run: echo "${{ steps.previous-tag.outputs.tagg }}"
#      - name: Make Release Dir
#        run: |
#
#          # TODO <-= this should be the _current_ major version
#          mkdir releases/v${{ steps.next_version.outputs.version }}
#          cp -R src/imports/ releases/v${{ steps.next_version.outputs.version }}
#          cp -R src/terra-core/ releases/v${{ steps.next_version.outputs.version }}
#          git config user.name "TIM Release Bot"
#          git config user.email "<>"
#          git add .
#          git commit -m 'Releasing version ${{ steps.next_version.outputs.version }}'
#          git push
#          echo ::set-output name=sha::$(git rev-parse HEAD)
#      - uses: zwaldowski/semver-release-action@v1
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#        with:
#          bump: minor
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          sha: ${{ steps.git_commit.outputs.sha }}
#          prefix: v
#


