name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compute Next Tag
        id: next_version
        uses: zwaldowski/semver-release-action@v2
        with:
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          prefix: v
      - name: Echo Next Tag
        run: echo "${{ steps.next_version.outputs.version }}"
      - name: Make Release Dir
        run: |
          mkdir releases/v${{ steps.next_version.outputs.version }}
          cp -R src/imports/ releases/v${{ steps.next_version.outputs.version }}
          cp -R src/terra-core/ releases/v${{ steps.next_version.outputs.version }}
          git config user.name "TIM Release Bot"
          git config user.email "<>>"
          git add .
          git commit -m 'Releasing version ${{ steps.next_version.outputs.version }}'
          git push
          echo ::set-output name=sha::$(git rev-parse HEAD)
      - uses: zwaldowski/semver-release-action@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}
          prefix: v



