name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compute Next Tag
        id: compute-next-tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_strategy: none
      - name: Echo Next Tag
        run: echo "The next tag is ${{ steps.compute-next-tag.outputs.tag }}"
