name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all tags + history
      - name: Get previous tag
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: "${{ steps.previous-tag.outputs.version }}"
      - run: echo "${{ steps.semver_parser.outputs.major }} ${{ steps.semver_parser.outputs.minor }} ${{ steps.semver_parser.outputs.patch }}"
#      - name: Update release dir
#        run: |
#          # TODO <-= this should be the _current_ major version
#          mkdir releases/v${{ steps.next_version.outputs.version }}
#          cp -R src/imports/ releases/v${{ steps.previous-tag.outputs.version }}
#          cp -R src/terra-core/ releases/v${{ steps.previous-tag.outputs.version }}
#          git config user.name "TIM Release Bot"
#          git config user.email "<>"
#          git add .
#          git commit -m 'Releasing version ${{ steps.next_version.outputs.version }}'
#          git push
#          echo ::set-output name=sha::$(git rev-parse HEAD)
#      - uses: zwaldowski/semver-release-action@v1
#        env:
#          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#        with:
#          bump: minor
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          sha: ${{ steps.git_commit.outputs.sha }}
#          prefix: v
#


