name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all tags + history
      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo "${{ steps.previous_tag.outputs.tag }}"
      - name: Parse current version
        id: parse_current_tag
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.current_tag.outputs.tag }}
      - id: next_tag
        uses: zwaldowski/semver-release-action@v1
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Update release dir
        run: |
          cp -R src/imports/ releases/v${{ steps.parse_current_tag.outputs.major }}
          cp -R src/terra-core/ releases/v${{ steps.parse_current_tag.outputs.major }}
          git config user.name "TIM Release Bot"
          git config user.email "<>"
          git add .
          git commit -m 'Releasing version ${{ steps.next_tag.outputs.version }}' || true
          git tag ${{ steps.next_tag.outputs.version }}
          git push origin ${{ steps.next_tag.outputs.version }}


