name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compute Next Tag
        id: next_version
        uses: zwaldowski/semver-release-action@v2
        bump: minor
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        prefix: v

      - name: Echo Next Tag
        run: echo "${{ steps.next_version.outputs.version }}"
