name: Release Minor Version

on:
  workflow_dispatch:

jobs:
  release-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compute Next Tag
        uses: hennejg/github-tag-action@v4.2.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - name: Echo Next Tag
        run: echo "The next tag is ${{ steps.compute-next-tag.outputs.tag }}"
